name: Docs
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Git changelog build
        run: git changelog > CHANGELOG.md
      - name: Build site
        run: mkdocs build --strict
      - name: Push to github sites
        run: mkdocs gh-deploy